CREATE TABLE PRODUCTS (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL
)

ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID);

INSERT INTO PRODUCTS(ID, NAME) VALUES(1, 'This text contains special characters: é ç ã á à í');